// RACES
export const GET_RACES_SUCCESS = 'GET_RACES_SUCCESS'
export const GET_RACES_ERROR = 'GET_RACES_ERROR'

export const UPDATE_RACES = 'UPDATE_RACES'
export const FETCH_RACES = 'FETCH_RACES'
export const CLICK_RACE = 'CLICK_RACE'